<<<<<<< HEAD
# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=trailb
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge
=======
services:
  # Serviço para o aplicativo Spring Boot
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  # Serviço para o banco de dados MySQL
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trailb
      MYSQL_USER: admntrailb
      MYSQL_PASSWORD: trailb1.2.3
>>>>>>> 52b050793daab5f826c07d98f30adf56c59112ea
